#!/usr/bin/env python

n = int(input())

# Import the reduce() function
from functools import reduce
def factorial(n):
    if n == 0:
        return 1
    else:
        return reduce(lambda x,y: x*y , range(1,n+1))

print(factorial(n))
